### ISSUE TITLE
"Շպարգալկա" -> "Հուշաթերթիկ"

### ISSUE THREAD

**Issue by otanim** [iteratehackerspace/cheatsheet#26]
"Շպարգալկա" isn't Armenian word (it's translit version of Russian "шпаргалка"). The correct is "Հուշաթերթիկ".

replace all "Շպարգալկա" to "Հուշաթերթիկ".

**Comment by fxfactorial** [comment]
This is becoming a bit controversial lol, we should have a poll vote.

**Comment by otanim** [comment]
well, there is a dictionary, which said that it has a translation:
http://www.nayiri.com/imagedDictionaryBrowser.jsp?dictionaryId=37&query=шпаргалка

**Comment by fxfactorial** [comment]
Well technical language in Armenian is missing, so if this is the correct word but an incorrect one is being used then I want us to use the correct Armenian word. This strengthens the Armenian language and builds up a technical language.

**Comment by otanim** [comment]
@Hrant-Khachatrian, @hanumanum, @norayr

**Comment by kalipsobznuni** [comment]
The word is correct it's just not what we use and it is not only about tech.
Like we never say students used "Հուշաթերթիկ" right.
So now it's more about what we prioritize: the lost Armenian word or the word everybody understands and associates with the actual meaning.

**Comment by fxfactorial** [comment]
I vote for the lost Armenian word, people can learn. If I'm learning, then can learn too.

**Comment by otanim** [comment]
A lot of students and young generation became degraded more and more․
The guys that I've mentioned above, they are professionals in this area, I hope they will answer soon :)

**Comment by fxfactorial** [comment]
I'm willing to bet they will agree

**Comment by kalipsobznuni** [comment]
true, have no arguments against learning

**Comment by norayr** [comment]
>The word is correct it's just not what we use and it is not only about tech.

I don't know what do you, or people around you use, but we at work or with friends describe cheatsheets as հուշաթերթիկ. It's a normal word for people I communicate with. I don't remember when last time I've heard the word շպարգալկա, may be in soviet russian school in eighties. However I understand that people groups are different, so once when I asked a friend to turn on օդորակիչ, which is a completely normal word for me, my coworkers and my friends, one of his guests said 'why do you use that word if there's կոնդիցիոներ' and we were surprised by that question, because it did not come to our minds to use the word she mentioned while there's a nice word we use in everyday life and are used to.

Today my friend's windshield have been damaged by the huge piece of ice fallen from the roof. He said about that accident by using the word դիմապակի. It didn't come to his mind to use something else while in this case I perfectly realize that the majority of the people would express the same with other words. However, the same majority would perfectly understand դիմապակի because it's intuitively understandable to any Armenian. Another example, once I was chatting with my mother, had to make a suggestion about document formatting. I used the words թավատառ and շեղատառ and then realized, that in case I would use words 'bold' or 'italic', I would need to explain her what those words mean. Now, by using Armenian, intuitively understandable words I did not have a reason to make an extra effort, and she did not feel stupid or illiterate because she understood me.

**Comment by norayr** [comment]
also, it's a tradition we know since Mashtots times, to translate words instead of importing roots, that's why we have քաղաքականություն, and not պոլիտիկա. the tradition continued in 20th century, so we have ուղղաթիռ, while let's say in Turkish it's described as 'helikopter' and in Azerbaijani the word is 'vertolyot'. Also, հեծանիվ is a nice example - when the word was introduced, it was widely criticized - 'who would use that ridiculous word?' - people were saying. Today any kid uses that word, and again, it's intuitively understandable for those who knows Armenian, because there we can hear հեծել and անիվ. Just more two satoshis from me. Thank you.

**Comment by fxfactorial** [comment]
@norayr Just to be clear, you agree that we should change it to: հուշաթերթիկ?

**Comment by norayr** [comment]
yes. (:

**Comment by norayr** [comment]
btw about the computer related armenian, i try to maintain a list, assembled from different sources, including microsoft windows translations, tarumian's dictionary of terms, etc, which is located at https://github.com/norayr/noch-armenian-dictionary. also, btw, repository is translated as շտեմարան.

**Comment by otanim** [comment]
@norayr thanks! I've searched for this.
If you've remeber @hanuman has been created a list it translations: http://hy-it.org/help-it-translators/
but unfortunately some of good links are missing. This list will really help contributors to make a clean translation :)

**Comment by fxfactorial** [comment]
Okay, settled :)
